runtime: python27
api_version: 1
threadsafe: yes

builtins:
- deferred: on
- appstats: on
- remote_api: on

libraries:
- name: ssl
  version: latest
- name: pycrypto
  version: 2.6

handlers:
- url: /_ah/queue/deferred
  script: google.appengine.ext.deferred.deferred.application
  login: admin

- url: /favicon\.ico
  static_files: app/static/favicon.ico
  upload: favicon\.ico

- url: /static
  static_dir: app/static

- url: .*
  script: main.app
  secure: always

env_variables:
  GAE_USE_SOCKETS_HTTPLIB: 'anyvalue'
  FIREBASE_PROJECT_ID: 'redneighbor-b'
  CLOUDINARY_URL: 'cloudinary://733635521161972:rJljH4QNmSF0ZrfzK2tQDw4B4Gg@dl47rxobq'
  TELEGRAM_TOKEN: '313362333:AAHdAhSO29g_cMY3qDzLDa4A3uM4F5lzWmk'

Temporary workaround around gcloud issue
skip_files:
  - ^venv/.*$
